---
- hosts: web
  roles: 
    - webserver
  tasks:
    - name: restarting webserver
      service: name=httpd state=restarted
    - name: restarting Firewall
      service: name=firewalld state=restarted
    - selinux: state=disabled
- hosts: db
  roles: 
    - database
  tasks:
    - name: restarting mariadb
      service: name=mariadb.service state=restarted
    - name: restarting Firewall
      service: name=firewalld state=restarted 
    - selinux: state=disabled
