---
# tasks file for database
- name: Installing mariadb
  package: name=mariadb-server state=present
- name: Installing epel-relese
  package: name=epel-release state=present
- name: Installing pip
  package: name=python-pip state=present
- name: installing MySQL-python
  package: name=MySQL-python state=present
- name: Staring mariadb
  service: name=mariadb.service state=started
- name: creating database
  mysql_db:
    name: sample
    state: present
- name: creating database_user
  mysql_user: 
    name: mediauser
    password: Ne0aP1p2PHE9s
    priv: '*.*:ALL'
    state: present
- name: adding mysql_port
  firewalld:
    port: 3306/tcp
    permanent: true
    state: enabled
